require: 
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - db/**/*
    - config/initializers/*
    - bin/bundle
    - bin/yarn
    - app/models/application_record.rb
    - app/mailers/application_mailer.rb
    - config/application.rb
