require: 
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - db/**/*
    - config/initializers/*
    - bin/bundle
    - bin/yarn
    - app/models/application_record.rb
    - app/mailers/application_mailer.rb
    - config/application.rb
    - spec/rails_helper.rb
    - lib/tasks/fly.rake

Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/users/registrations_controller.rb